//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETCliente", Namespace="http://schemas.datacontract.org/2004/07/PruebaMauricioJimenezQ.Entidades")]
    [System.SerializableAttribute()]
    public partial class ETCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((this.IdentificacionField.Equals(value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETArticulo", Namespace="http://schemas.datacontract.org/2004/07/PruebaMauricioJimenezQ.Entidades")]
    [System.SerializableAttribute()]
    public partial class ETArticulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ArticuloIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ArticuloId {
            get {
                return this.ArticuloIdField;
            }
            set {
                if ((this.ArticuloIdField.Equals(value) != true)) {
                    this.ArticuloIdField = value;
                    this.RaisePropertyChanged("ArticuloId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETFactura", Namespace="http://schemas.datacontract.org/2004/07/PruebaMauricioJimenezQ.Entidades")]
    [System.SerializableAttribute()]
    public partial class ETFactura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsecutivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FacturaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalFacturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Consecutivo {
            get {
                return this.ConsecutivoField;
            }
            set {
                if ((this.ConsecutivoField.Equals(value) != true)) {
                    this.ConsecutivoField = value;
                    this.RaisePropertyChanged("Consecutivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FacturaId {
            get {
                return this.FacturaIdField;
            }
            set {
                if ((this.FacturaIdField.Equals(value) != true)) {
                    this.FacturaIdField = value;
                    this.RaisePropertyChanged("FacturaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pago {
            get {
                return this.PagoField;
            }
            set {
                if ((this.PagoField.Equals(value) != true)) {
                    this.PagoField = value;
                    this.RaisePropertyChanged("Pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalFactura {
            get {
                return this.TotalFacturaField;
            }
            set {
                if ((this.TotalFacturaField.Equals(value) != true)) {
                    this.TotalFacturaField = value;
                    this.RaisePropertyChanged("TotalFactura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETLineadetalle", Namespace="http://schemas.datacontract.org/2004/07/PruebaMauricioJimenezQ.Entidades")]
    [System.SerializableAttribute()]
    public partial class ETLineadetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ArticuloIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FacturaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LineadetalleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalLineaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ArticuloId {
            get {
                return this.ArticuloIdField;
            }
            set {
                if ((this.ArticuloIdField.Equals(value) != true)) {
                    this.ArticuloIdField = value;
                    this.RaisePropertyChanged("ArticuloId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FacturaId {
            get {
                return this.FacturaIdField;
            }
            set {
                if ((this.FacturaIdField.Equals(value) != true)) {
                    this.FacturaIdField = value;
                    this.RaisePropertyChanged("FacturaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LineadetalleId {
            get {
                return this.LineadetalleIdField;
            }
            set {
                if ((this.LineadetalleIdField.Equals(value) != true)) {
                    this.LineadetalleIdField = value;
                    this.RaisePropertyChanged("LineadetalleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreArticulo {
            get {
                return this.NombreArticuloField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArticuloField, value) != true)) {
                    this.NombreArticuloField = value;
                    this.RaisePropertyChanged("NombreArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalLinea {
            get {
                return this.TotalLineaField;
            }
            set {
                if ((this.TotalLineaField.Equals(value) != true)) {
                    this.TotalLineaField = value;
                    this.RaisePropertyChanged("TotalLinea");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarCliente", ReplyAction="http://tempuri.org/IService1/RegistrarClienteResponse")]
        void RegistrarCliente(int Codigo, int Identificacion, string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarCliente", ReplyAction="http://tempuri.org/IService1/RegistrarClienteResponse")]
        System.Threading.Tasks.Task RegistrarClienteAsync(int Codigo, int Identificacion, string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCliente", ReplyAction="http://tempuri.org/IService1/ActualizarClienteResponse")]
        void ActualizarCliente(string ClienteId, int Codigo, int Identificacion, string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCliente", ReplyAction="http://tempuri.org/IService1/ActualizarClienteResponse")]
        System.Threading.Tasks.Task ActualizarClienteAsync(string ClienteId, int Codigo, int Identificacion, string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerClienteOClientes", ReplyAction="http://tempuri.org/IService1/ObtenerClienteOClientesResponse")]
        PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETCliente[] ObtenerClienteOClientes(string ClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerClienteOClientes", ReplyAction="http://tempuri.org/IService1/ObtenerClienteOClientesResponse")]
        System.Threading.Tasks.Task<PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETCliente[]> ObtenerClienteOClientesAsync(string ClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCliente", ReplyAction="http://tempuri.org/IService1/EliminarClienteResponse")]
        void EliminarCliente(string ClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCliente", ReplyAction="http://tempuri.org/IService1/EliminarClienteResponse")]
        System.Threading.Tasks.Task EliminarClienteAsync(string ClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarArticulo", ReplyAction="http://tempuri.org/IService1/RegistrarArticuloResponse")]
        void RegistrarArticulo(int Codigo, string Nombre, decimal Precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarArticulo", ReplyAction="http://tempuri.org/IService1/RegistrarArticuloResponse")]
        System.Threading.Tasks.Task RegistrarArticuloAsync(int Codigo, string Nombre, decimal Precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarArticulo", ReplyAction="http://tempuri.org/IService1/ActualizarArticuloResponse")]
        void ActualizarArticulo(string ArticuloId, int Codigo, string Nombre, decimal Precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarArticulo", ReplyAction="http://tempuri.org/IService1/ActualizarArticuloResponse")]
        System.Threading.Tasks.Task ActualizarArticuloAsync(string ArticuloId, int Codigo, string Nombre, decimal Precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerArticuloOArticulos", ReplyAction="http://tempuri.org/IService1/ObtenerArticuloOArticulosResponse")]
        PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETArticulo[] ObtenerArticuloOArticulos(string ArticuloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerArticuloOArticulos", ReplyAction="http://tempuri.org/IService1/ObtenerArticuloOArticulosResponse")]
        System.Threading.Tasks.Task<PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETArticulo[]> ObtenerArticuloOArticulosAsync(string ArticuloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarArticulo", ReplyAction="http://tempuri.org/IService1/EliminarArticuloResponse")]
        void EliminarArticulo(string ArticuloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarArticulo", ReplyAction="http://tempuri.org/IService1/EliminarArticuloResponse")]
        System.Threading.Tasks.Task EliminarArticuloAsync(string ArticuloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarFactura", ReplyAction="http://tempuri.org/IService1/RegistrarFacturaResponse")]
        void RegistrarFactura(string ClienteId, decimal TotalFactura, bool Pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarFactura", ReplyAction="http://tempuri.org/IService1/RegistrarFacturaResponse")]
        System.Threading.Tasks.Task RegistrarFacturaAsync(string ClienteId, decimal TotalFactura, bool Pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarFactura", ReplyAction="http://tempuri.org/IService1/ActualizarFacturaResponse")]
        void ActualizarFactura(string FacturaId, string ClienteId, decimal TotalFactura, bool Pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarFactura", ReplyAction="http://tempuri.org/IService1/ActualizarFacturaResponse")]
        System.Threading.Tasks.Task ActualizarFacturaAsync(string FacturaId, string ClienteId, decimal TotalFactura, bool Pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerFacturaOFacturas", ReplyAction="http://tempuri.org/IService1/ObtenerFacturaOFacturasResponse")]
        PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETFactura[] ObtenerFacturaOFacturas(string FacturaId, string ClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerFacturaOFacturas", ReplyAction="http://tempuri.org/IService1/ObtenerFacturaOFacturasResponse")]
        System.Threading.Tasks.Task<PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETFactura[]> ObtenerFacturaOFacturasAsync(string FacturaId, string ClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarFactura", ReplyAction="http://tempuri.org/IService1/EliminarFacturaResponse")]
        void EliminarFactura(string FacturaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarFactura", ReplyAction="http://tempuri.org/IService1/EliminarFacturaResponse")]
        System.Threading.Tasks.Task EliminarFacturaAsync(string FacturaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarLineadetalle", ReplyAction="http://tempuri.org/IService1/RegistrarLineadetalleResponse")]
        void RegistrarLineadetalle(string FacturaId, string ArticuloId, decimal PrecioUnitario, int Cantidad, decimal TotalLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarLineadetalle", ReplyAction="http://tempuri.org/IService1/RegistrarLineadetalleResponse")]
        System.Threading.Tasks.Task RegistrarLineadetalleAsync(string FacturaId, string ArticuloId, decimal PrecioUnitario, int Cantidad, decimal TotalLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarLineadetalle", ReplyAction="http://tempuri.org/IService1/ActualizarLineadetalleResponse")]
        void ActualizarLineadetalle(string LineaDetalleId, string FacturaId, string ArticuloId, decimal PrecioUnitario, int Cantidad, decimal TotalLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarLineadetalle", ReplyAction="http://tempuri.org/IService1/ActualizarLineadetalleResponse")]
        System.Threading.Tasks.Task ActualizarLineadetalleAsync(string LineaDetalleId, string FacturaId, string ArticuloId, decimal PrecioUnitario, int Cantidad, decimal TotalLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerLineadetalleOLineadetalles", ReplyAction="http://tempuri.org/IService1/ObtenerLineadetalleOLineadetallesResponse")]
        PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETLineadetalle[] ObtenerLineadetalleOLineadetalles(string FacturaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerLineadetalleOLineadetalles", ReplyAction="http://tempuri.org/IService1/ObtenerLineadetalleOLineadetallesResponse")]
        System.Threading.Tasks.Task<PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETLineadetalle[]> ObtenerLineadetalleOLineadetallesAsync(string FacturaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarLineadetalle", ReplyAction="http://tempuri.org/IService1/EliminarLineadetalleResponse")]
        void EliminarLineadetalle(string LineadetalleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarLineadetalle", ReplyAction="http://tempuri.org/IService1/EliminarLineadetalleResponse")]
        System.Threading.Tasks.Task EliminarLineadetalleAsync(string LineadetalleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.IService1>, PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistrarCliente(int Codigo, int Identificacion, string Nombre) {
            base.Channel.RegistrarCliente(Codigo, Identificacion, Nombre);
        }
        
        public System.Threading.Tasks.Task RegistrarClienteAsync(int Codigo, int Identificacion, string Nombre) {
            return base.Channel.RegistrarClienteAsync(Codigo, Identificacion, Nombre);
        }
        
        public void ActualizarCliente(string ClienteId, int Codigo, int Identificacion, string Nombre) {
            base.Channel.ActualizarCliente(ClienteId, Codigo, Identificacion, Nombre);
        }
        
        public System.Threading.Tasks.Task ActualizarClienteAsync(string ClienteId, int Codigo, int Identificacion, string Nombre) {
            return base.Channel.ActualizarClienteAsync(ClienteId, Codigo, Identificacion, Nombre);
        }
        
        public PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETCliente[] ObtenerClienteOClientes(string ClienteId) {
            return base.Channel.ObtenerClienteOClientes(ClienteId);
        }
        
        public System.Threading.Tasks.Task<PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETCliente[]> ObtenerClienteOClientesAsync(string ClienteId) {
            return base.Channel.ObtenerClienteOClientesAsync(ClienteId);
        }
        
        public void EliminarCliente(string ClienteId) {
            base.Channel.EliminarCliente(ClienteId);
        }
        
        public System.Threading.Tasks.Task EliminarClienteAsync(string ClienteId) {
            return base.Channel.EliminarClienteAsync(ClienteId);
        }
        
        public void RegistrarArticulo(int Codigo, string Nombre, decimal Precio) {
            base.Channel.RegistrarArticulo(Codigo, Nombre, Precio);
        }
        
        public System.Threading.Tasks.Task RegistrarArticuloAsync(int Codigo, string Nombre, decimal Precio) {
            return base.Channel.RegistrarArticuloAsync(Codigo, Nombre, Precio);
        }
        
        public void ActualizarArticulo(string ArticuloId, int Codigo, string Nombre, decimal Precio) {
            base.Channel.ActualizarArticulo(ArticuloId, Codigo, Nombre, Precio);
        }
        
        public System.Threading.Tasks.Task ActualizarArticuloAsync(string ArticuloId, int Codigo, string Nombre, decimal Precio) {
            return base.Channel.ActualizarArticuloAsync(ArticuloId, Codigo, Nombre, Precio);
        }
        
        public PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETArticulo[] ObtenerArticuloOArticulos(string ArticuloId) {
            return base.Channel.ObtenerArticuloOArticulos(ArticuloId);
        }
        
        public System.Threading.Tasks.Task<PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETArticulo[]> ObtenerArticuloOArticulosAsync(string ArticuloId) {
            return base.Channel.ObtenerArticuloOArticulosAsync(ArticuloId);
        }
        
        public void EliminarArticulo(string ArticuloId) {
            base.Channel.EliminarArticulo(ArticuloId);
        }
        
        public System.Threading.Tasks.Task EliminarArticuloAsync(string ArticuloId) {
            return base.Channel.EliminarArticuloAsync(ArticuloId);
        }
        
        public void RegistrarFactura(string ClienteId, decimal TotalFactura, bool Pago) {
            base.Channel.RegistrarFactura(ClienteId, TotalFactura, Pago);
        }
        
        public System.Threading.Tasks.Task RegistrarFacturaAsync(string ClienteId, decimal TotalFactura, bool Pago) {
            return base.Channel.RegistrarFacturaAsync(ClienteId, TotalFactura, Pago);
        }
        
        public void ActualizarFactura(string FacturaId, string ClienteId, decimal TotalFactura, bool Pago) {
            base.Channel.ActualizarFactura(FacturaId, ClienteId, TotalFactura, Pago);
        }
        
        public System.Threading.Tasks.Task ActualizarFacturaAsync(string FacturaId, string ClienteId, decimal TotalFactura, bool Pago) {
            return base.Channel.ActualizarFacturaAsync(FacturaId, ClienteId, TotalFactura, Pago);
        }
        
        public PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETFactura[] ObtenerFacturaOFacturas(string FacturaId, string ClienteId) {
            return base.Channel.ObtenerFacturaOFacturas(FacturaId, ClienteId);
        }
        
        public System.Threading.Tasks.Task<PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETFactura[]> ObtenerFacturaOFacturasAsync(string FacturaId, string ClienteId) {
            return base.Channel.ObtenerFacturaOFacturasAsync(FacturaId, ClienteId);
        }
        
        public void EliminarFactura(string FacturaId) {
            base.Channel.EliminarFactura(FacturaId);
        }
        
        public System.Threading.Tasks.Task EliminarFacturaAsync(string FacturaId) {
            return base.Channel.EliminarFacturaAsync(FacturaId);
        }
        
        public void RegistrarLineadetalle(string FacturaId, string ArticuloId, decimal PrecioUnitario, int Cantidad, decimal TotalLinea) {
            base.Channel.RegistrarLineadetalle(FacturaId, ArticuloId, PrecioUnitario, Cantidad, TotalLinea);
        }
        
        public System.Threading.Tasks.Task RegistrarLineadetalleAsync(string FacturaId, string ArticuloId, decimal PrecioUnitario, int Cantidad, decimal TotalLinea) {
            return base.Channel.RegistrarLineadetalleAsync(FacturaId, ArticuloId, PrecioUnitario, Cantidad, TotalLinea);
        }
        
        public void ActualizarLineadetalle(string LineaDetalleId, string FacturaId, string ArticuloId, decimal PrecioUnitario, int Cantidad, decimal TotalLinea) {
            base.Channel.ActualizarLineadetalle(LineaDetalleId, FacturaId, ArticuloId, PrecioUnitario, Cantidad, TotalLinea);
        }
        
        public System.Threading.Tasks.Task ActualizarLineadetalleAsync(string LineaDetalleId, string FacturaId, string ArticuloId, decimal PrecioUnitario, int Cantidad, decimal TotalLinea) {
            return base.Channel.ActualizarLineadetalleAsync(LineaDetalleId, FacturaId, ArticuloId, PrecioUnitario, Cantidad, TotalLinea);
        }
        
        public PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETLineadetalle[] ObtenerLineadetalleOLineadetalles(string FacturaId) {
            return base.Channel.ObtenerLineadetalleOLineadetalles(FacturaId);
        }
        
        public System.Threading.Tasks.Task<PruebaMauricioJimenezQ.PaginaWeb.ServiceReference1.ETLineadetalle[]> ObtenerLineadetalleOLineadetallesAsync(string FacturaId) {
            return base.Channel.ObtenerLineadetalleOLineadetallesAsync(FacturaId);
        }
        
        public void EliminarLineadetalle(string LineadetalleId) {
            base.Channel.EliminarLineadetalle(LineadetalleId);
        }
        
        public System.Threading.Tasks.Task EliminarLineadetalleAsync(string LineadetalleId) {
            return base.Channel.EliminarLineadetalleAsync(LineadetalleId);
        }
    }
}
